{% set name = "django-pint" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: da1ae98910b4156cdb5bb1f9590bf1d12fd590fef1a864722d9b941265bd1a34

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - wheel
    - pip
  run:
    - python >=3.8
    - django >=3.2
    - pint >=0.16

test:
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://github.com/CarliJoy/django-pint/
  summary: '"Quantity Field for Django using pint library for automated unit conversions"'
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - alexpilot11
    - BryanAke
